### ISSUE TITLE
🚀 Feature: Basic PWA App Implementation

### ISSUE THREAD

**Issue by lukaszkowalik2** [lukaszkowalik2/pwa-ignite#4]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/lukaszkowalik2/pwa-ignite/issues?q=is%3Aissue) and found none that matched my issue.

#### Description:
The goal of this issue is to create a basic Progressive Web App (PWA) with support for multiple platforms and translations.

#### Tasks:
- [x] Add installation dialog for iPhone.
- [x] Add installation dialog for Android.
- [x] Implement app translations for multiple languages.
- [x] Add basic PWA support for Chrome and Safari (iOS).
- [x] Create documentation on installing and using the PWA.

**Comment by lukaszkowalik2** [comment]
Added it in this [PR](https://github.com/lukaszkowalik2/pwa-ignite/pull/6)
